const products = [
    {
      id: 1,
      title: 'Persi Džekson i bogovi Olimpa I - Kradljivac munje',
      price: 800,
      img: './images/pdz.jpg',
      desc: `Persi Džekson će po ko zna koji put biti izbačen iz škole. Međutim, to nije njegov najveći problem. Čudovišta iz grčkih mitova i bogovi Olimpa kao da su rešili da se sa stranica Persijevih udžbenika presele u njegov život i da ga zagorčaju. Da sve bude još gore, on je neke od njih mnogo naljutio. Ukradena je Zevsova vrhovna munja, a Persi je glavni osumnjičeni.`,
      omiljena: 0,
    },
    {
      id: 2,
      title: 'Hari Poter i ukleto dete',
      price: 1200 ,
      img: './images/hp.jpg',
      desc: `evetnaest godina nakon što su Hari Poter, Ron Vizli i Hermiona Grejndžer spasli čarobnjački svet, njih troje upuštaju se u novu, neverovatnu pustolovinu, u kojoj će im se pridružiti hrabra generacija koja sada pohađa Hogvorts, školu za veštičarenje i čarobnjaštvo. `,
      omiljena: 0,
    },
    {
      id: 3,
      title: 'Kompas ishrane',
      price: 688,
      img: './images/ki.jpg',
      desc: `Kada je Bas Kast, novinar posvećen naučnim temama, osetio probadanje u grudima, ozbiljno se zabrinuo i ubrzo mu se nametnulo ključno pitanje: da li je lošom ishranom upropastio svoje zdravlje? Odlučio je da korenito promeni način ishrane. Međutim, šta stvarno znači biti zdrav?`,
      omiljena: 0,
    },
    {
      id: 4,
      title: 'Persi Džekson i bogovi Olimpa V - Poslednji bog Olimpa',
      price: 800,
      img: './images/pdz-2.jpg',
      desc: `Tokom čitave godine polutani se pripremaju za bitku protiv Titana, znajući da će teško izvojevati pobedu. Kronova armija je jača nego ikada ranije, a sa svakim bogom i polutanom kojeg regrutuje, moć Titanovog zla samo raste. Dok se Olimpljani odupiru zastrašujućem čudovištu Tifonu, Kron otpočinje svoj napad na Njujork, tako da je sam Olimp bez odbrane`,
      omiljena: 0,
    },
    {
      id: 5,
      title: 'Hari Poter i Relikvije Smrti',
      price: 1800,
      img: './images/hp-1.jpg',
      desc: `Sedajući u prikolicu Hagridovog motora i napustivši Šimširovu ulicu poslednji put, Hari Poter zna da Voldemor i Smrtožderi nisu daleko za njim. Čini koje su ga do sada štitile su razvejane, a on ne može više da se skriva. Mračni gospodar uvlači strah u kosti svima do kojih je Hariju stalo i, kako bi ga zaustavio, Hari mora da pronađe i uništi preostale Horkrukse.`,
      omiljena: 0,
    },
    {
      id: 6,
      title: 'Feng šui: kineska mudrost i balkanska tradicija',
      price: 400,
      img: './images/fs.jpg',
      desc: `Feng šui je drevna nauka koja se bavi odnosom čoveka sa prostorom i kosmičkom energijom. Primenjuje se u svim oblastima života: prilikom pronalaženja povoljne lokacije za stan, kuću ili kancelariju, u dekorisanju enterijera u kojem se živi ili radi. `,
      omiljena: 0,
    },
    {
      id: 7,
      title: 'Persi Džekson i bogovi Olimpa III - Titanova kletva',
      price: 600,
      img: './images/pdz-1.jpg',
      desc: `Kada Persi Džekson primi hitan, paničan poziv od svog prijatelja Grovera, odmah se priprema za akciju. Zna da će mu biti neophodni: pomoć njegovih prijatelja polutana, njegov pouzdani mač od nebeske bronze Rasparač, i… mama, koja će ga kolima povesti u ovu avanturu. `,
      omiljena: 0,
    },
    {
      id: 8,
      title: 'Serviraj za pobedu',
      price: 500,
      img: './images/ndj.jpg',
      desc: `Četrnaestodnevni plan bezglutenske ishrane za vrhunska fizička dostignuća i mentalnu snagu.Novak Đoković je, po mišljenju sportskih novinara, 2011. ostvario najbolju igračku sezonu u istoriji tenisa. Osvojio je deset turnira, od toga tri grend slem titule, i ostvario niz od četrdeset tri uzastopne pobede`,
      omiljena: 0,
    },
    {
      id: 9,
      title: 'Lenji Genije',
      price: 700,
      img: './images/lg.jpg',
      desc: `Bestseler New York Timesa.Posvetite se onome što je važno, zaboravite nevažno i završavajte poslove.Biti Lenji Genije ne znači raditi više ili manje. Suština je da radite ono što je vama važno.`,
      omiljena: 0,
    },
    {
      id: 10,
      title: 'Hari Poter i Polukrvni Princ',
      price: 1500,
      img: './images/hp-2.jpg',
      desc: `KADA SE JEDNE letnje večeri Dambldor pojavio u Šimširovoj ulici, ruka kojom koristi magični štapić bila je usahla i pocrnela. Ali on nije objasnio Hariju šta je posredi. Tajne i sumnje šire se čarobnjačkim svetom poput šumskog požara, a čak i sam Hogvorts nije više bezbedno utočište. Hari je ubeđen da Melfoj nosi Mračni znak.`,
      omiljena: 0,
    },
    {
      id: 11,
      title: 'Šta sve novac ne može da kupi?',
      price: 1000 ,
      img: './images/no.jpg',
      desc: `Treba li da se zabrinemo zbog toga što se krećemo prema društvu u kome je sve na prodaju? Kako možemo da odlučimo koja dobra treba da se kupuju i prodaju, a kojima treba da upravljaju netržišne vrednosti? Gde to para ne bi trebalo da vrti?`,
      omiljena: 0,
    },
    {
      id: 12,
      title: 'Optimizam i zdravlje: Šta nauka zna o blagotvornosti pozitivnog mišljenja',
      price: 535,
      img: './images/op.jpg',
      desc: `Jedna od najvrednijih investicija, koja traži malo ulaganja a donosi mnogo dobiti je da naučite da osećate i razmišljate pozitivno. Psihijatar Rohas Markos razmatra sve aspekte pozitivnog razmišljanja i opisuje dokazane strategije za promovisanje optimističnog ali realnog raspoloženja.`,
      omiljena: 0,
    },
    {
      id: 13,
      title: '10 minuta i 38 sekundi na ovom čudnom svetu',
      price: 700,
      img: './images/cs.jpg',
      desc: `vaki minut nakon njene smrti donosi Lejli neku čulnu uspomenu: na ukus začinjenog gulaša od mesa koze koju je njen otac prineo na žrtvu u čast rođenja dugo čekanog sina; na prizor šerpe u kojoj vri šećer kojim su žene depilirale noge kad muškarci odu u džamiju; na miris kafe s kardamonom koju je pila u bordelu u kom je radila. Sa svakom uspomenom priseća se i prijatelja koje je stekla u odsudnim trenucima u svom životu – prijatelja koji sad očajnički pokušavaju da je nađu.`,
      omiljena: 0,
    },
    {
      id: 14,
      title: 'Madam Pompadur',
      price: 1100,
      img: './images/mp.jpg',
      desc: `Neverovatna sudbina markize od Pompadura istinita je priča. Kako je ova devojčica bez pedigrea, zahvaljujući svojoj lepoti, britkom umu, ambiciji i umeću zavođenja, postala centralna figura francuske političke scene?`,
      omiljena: 0,
    },
    {
      id: 15,
      title: 'Beograd',
      price: 1200,
      img: './images/bg.jpg',
      desc: `Trojica dvanaestogodišnjaka, sticajem okolnosti, istog dana, dvadesetosmog avgusta 1899. stižu u Beograd. Stefana Vukobrata otac brani od gladi i iz Hercegovine i šalje kod bogatog kuma. Strahinju Milosavljevića sklanjaju kod tetke, od krvne osvete sa Kosova, jer mu je otac, zatekavši ga u krađi šume, ubio komšiju Albanca. Pavle Kozarević dolazi iz Budimpešte, prateći oca koji ima nameru da pomogne u stvaranju moderne srpske države i njenoj evropeizaciji.`,
      omiljena: 0,
    },
    {
      id: 16,
      title: 'Kroz pustinju i prašumu',
      price: 990,
      img: './images/kpp.jpg',
      desc: `Kroz pustinju i prašumu je priča o dvoje drugara, Poljaku Staši (14) i Engleskinji Neli {8), čiji očevi rade kao inženjeri u Egiptu. Njih dvoje na putu otimaju Mahdijevi pobunjenici u Sudanu i moraće da prođu kroz niz pustoloviia kako bi se izbavili.`,
      omiljena: 0,
    },
    {
      id: 17,
      title: 'Preduzetništvo',
      price: 950,
      img: './images/pe.jpg',
      desc: `U savremenom dobu preduzetništva, veoma je primamljivo napustiti radno mesto i osnovati sopstveno preduzeće. Pre nego što to učinite, naučite sve što je moguće naučiti, i to od najboljih. Knjiga pred vama pruža vam tu mogućnost. `,
      omiljena: 0,
    },
    {
      id: 18,
      title: 'Bogati otac, siromašni otac - Ne radite za novac, neka novac radi za vas',
      price: 1320,
      img: './images/bo.jpg',
      desc: `Da biste, u finansijskom pogledu, izašli iz rovova i prešli u napad, morate da pročitate Bogati otac, siromašni otac. Kniga obiluje zdravim razumom i trgovačkom razboritošću, neophodnim za vašu finansijsku budućnost. Bogati otac, siromašni otac nije jedna od onih uobičajenih knjiga o novcu...`,
      omiljena: 0,
    },
  ];
  export default products;